server:
  port: 7013
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080

