### GET request to local server
GET http://localhost:7012/recommendation?productId=1
###

### POST request to local server
POST http://localhost:7012/recommendation
Content-Type: application/json

{
  "productId" : 1,
  "recommendationId": 1,
  "author": "Author 1",
  "rate" : 1,
  "content": "Content 1",
  "serviceAddress" : ""
}
###

### GET request to local server with id -1
GET http://localhost:7012/recommendation?productId=-1
###

### GET request to local server with missing parameter
GET http://localhost:7012/recommendation
###

### GET request to docker
GET http://localhost:8080/recommendation?productId=1
###

### GET product from docker
GET http://localhost:8080/product/3
###

### GET product from docker
GET http://localhost:8080/product/non-integer
###

### GET product from docker
GET http://localhost:8080/product/-3
###

### 404
GET http://localhost:7021/product/13
###

### 400
GET http://localhost:7021/product/not-integer
###