server:
  port: 7010

app:
  product-service:
    host: localhost
    port: 7021
  recommendation-service:
    host: localhost
    port: 7012
  review-service:
    host: localhost
    port: 7013


---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080


