server:
  port: 7021
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  data:
    mongodb:
      database: product-db
      host: localhost
      port: 27017

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
server:
  port: 8080

